"""
Stage 3: pairs.jsonl -> train/val/test in chat format.

Splits BY SOURCE BOOK, not by row. Chunks from one book share vocabulary,
translator idiom, and phrasing; a random row split leaks all of that across the
boundary and your eval reports a score the adapter has not earned.

That rule applies THREE ways, not two. An earlier version of this script held
out whole books from train -- correctly -- and then split each held-out book's
rows 50/50 into val and test. Train was clean, and val and test shared 232 of
their 235 source chunks: different questions, generated by the same teacher from
the same passages. So any decision made on val (a checkpoint, an early stop, a
hyperparameter) was effectively being made on test, and the "held-out" number
stopped being independent of anything.

It did no damage to the run that shipped -- 2 fixed epochs, final checkpoint,
nothing was ever selected on val -- but the method was wrong, and the moment
anyone added early stopping it would have started quietly inflating the headline.
Val and test must be independent OF EACH OTHER, not merely of train.

    python pipeline/03_split.py
"""
import collections, json, os, random, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import PAIRS, SYSTEM_PROMPT, split_path

random.seed(0)
HOLDOUT_EVERY = 9      # ~1 book in 9 held out, skipping the two biggest


def partition_holdout(held, by_src):
    """Deal the held-out BOOKS between val and test. Never a book's rows.

    Greedy largest-first into two bins, each book going to whichever bin has
    fewer rows so far. That balances row counts without ever letting a book
    straddle the boundary.

    Which bin becomes test: the one spanning MORE BOOKS. Test carries the
    headline held-out claims (perplexity vs the untuned base, the style
    metrics), and a claim resting on four books is worth more than the same
    claim resting on one. Ties go to the bin with more rows.
    """
    if len(held) < 2:
        sys.exit(f"only {len(held)} book(s) held out -- cannot give val and "
                 "test different books. Lower HOLDOUT_EVERY.")

    def rows(books):
        return sum(len(by_src[b]) for b in books)

    bins = ([], [])
    for b in sorted(held, key=lambda s: (-len(by_src[s]), s)):
        bins[0 if rows(bins[0]) <= rows(bins[1]) else 1].append(b)

    test_i = max((0, 1), key=lambda i: (len(bins[i]), rows(bins[i])))
    return set(bins[1 - test_i]), set(bins[test_i])


def main():
    rows = [json.loads(l) for l in open(PAIRS, encoding="utf-8")]
    by_src = collections.defaultdict(list)
    for r in rows:
        by_src[r["source"]].append(r)

    # Hold out whole books. Skip index 0-1 (the largest sources) so training
    # keeps the densest material; step through the rest for a mix of classical
    # and modern.
    books = sorted(by_src, key=lambda s: -len(by_src[s]))
    held = {books[i] for i in range(2, len(books), HOLDOUT_EVERY)}

    val_books, test_books = partition_holdout(held, by_src)

    split = {"train": [], "val": [], "test": []}
    for src, rs in by_src.items():
        if src in val_books:
            split["val"] += rs
        elif src in test_books:
            split["test"] += rs
        else:
            split["train"] += rs

    for name, rs in split.items():
        random.shuffle(rs)
        with open(split_path(name), "w", encoding="utf-8") as f:
            for r in rs:
                f.write(json.dumps({
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": r["question"]},
                        {"role": "assistant", "content": r["answer"]},
                    ],
                    "meta": {"source": r["source"], "type": r["type"],
                             "chunk_id": r["chunk_id"]},
                }, ensure_ascii=False) + "\n")
        print(f"{name:<6}{len(rs):>7,} pairs")

    print(f"\nheld-out books ({len(held)}) -- val and test share none of them:")
    for name, books in (("val", val_books), ("test", test_books)):
        n = sum(len(by_src[b]) for b in books)
        print(f"  {name:<5} {len(books)} book(s), {n:,} pairs")
        for b in sorted(books, key=lambda s: -len(by_src[s])):
            print(f"          {b}  ({len(by_src[b])} pairs)")

    t = collections.Counter(r["type"] for r in split["train"])
    print("\ntrain task mix:")
    for k, v in t.most_common():
        print(f"  {k:<18}{v:>6,}  {100*v/max(1,len(split['train'])):>5.1f}%")

    n = len(split["train"])
    if n < 4000:
        print(f"\n!! only {n:,} train pairs. Raise PAIRS_PER_CHUNK in stage 2 "
              "or accept a weaker adapter.")


if __name__ == "__main__":
    main()
